export const teamData = {
	mentors: [
		{
			name: 'Abin George',
			hackerName: 'LEO',
			image: '/images/team-member.jpg',
			description: 'Frontend dev, loves animation and clean UI.',
			domain: 'Web Security',
			linkedin: 'https://linkedin.com/in/ayushbenny',
			twitter: 'https://x.com/AyushBenny7',
			instagram: 'https://www.instagram.com/_ayx6h__/',
		},
		{
			name: 'Jyotiraditya',
			hackerName: 'GHOST',
			image: '/images/team-member.jpg',
			description: 'Backend specialist and system designer.',
			domain: 'System Design',
			linkedin: 'https://linkedin.com/in/leoxavier',
			twitter: 'https://twitter.com/ghost_dev',
		},
		{
			name: 'Rushi Wagh',
			hackerName: 'GHOST',
			image: '/images/team-member.jpg',
			description: 'Backend specialist and system designer.',
			domain: 'System Design',
			linkedin: 'https://linkedin.com/in/leoxavier',
			twitter: 'https://twitter.com/ghost_dev',
		},
		{
			name: 'Shantanu Jangale',
			hackerName: 'GHOST',
			image: '/images/team-member.jpg',
			description: 'Backend specialist and system designer.',
			domain: 'System Design',
			linkedin: 'https://linkedin.com/in/leoxavier',
			twitter: 'https://twitter.com/ghost_dev',
		},
		{
			name: 'Vishal Injewar',
			hackerName: 'GHOST',
			image: '/images/team-member.jpg',
			description: 'Backend specialist and system designer.',
			domain: 'System Design',
			linkedin: 'https://linkedin.com/in/leoxavier',
			twitter: 'https://twitter.com/ghost_dev',
		},
		{
			name: 'Yash',
			hackerName: 'GHOST',
			image: '/images/team-member.jpg',
			description: 'Backend specialist and system designer.',
			domain: 'System Design',
			linkedin: 'https://linkedin.com/in/leoxavier',
			twitter: 'https://twitter.com/ghost_dev',
		},
	],


	team: [
		{
			name: 'Amit Prajapati ',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Ansh Gadhia ',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},{
			name: 'Ayush Beenny ',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},{
			name: 'Onkar Sinha',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Vidyan Tidke',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Anshul Vairagade',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Tanush Bamnote',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Vedant Sayare',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Wansh Kumbhalkar',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Aditya Jadhav',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Anushka Pranjale',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Jay Gurav',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Kuber Deokar',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Manasvi Bonde',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Meetkumar',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Mohit Gurnule',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Mukul Suryawanshi',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Rewant Bajpee',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Riya Waghare',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Siddhant Mandal',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		{
			name: 'Tanmay Dhoke',
			hackerName: "Heyy",
			image: '/images/team-member.jpg',
			description: 'Cybersecurity analyst with a knack for forensics.',
			domain: 'Forensics',
			linkedin: 'https://linkedin.com/in/sarahkhan',
			instagram: 'https://instagram.com/sarah.forensics',
		},
		
	],
};